server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: postgres
      mode: always
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: matematika

  mail:
    host: smtp.devmail.email
    port: 465
    username: wildtrack
    password: OJe7Msf37S3DPKYcCO28

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

