custom:
  serverPath: ${SERVER_PATH:http://localhost:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: ${DB_PASS:POs7zG6FzHxiri2A4zsbQINSf1eoz4lN}
    username: ${DB_USERNAME:wildtrack_db_4a8m_user}
    url: ${DB_URL:jdbc:postgresql://dpg-cmbichol5elc73fc8l8g-a/wildtrack_db_4a8m}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

